services:
  epic_stream_frontend:
    container_name: epic_stream_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3005:3000
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
      - NEXT_PUBLIC_MEDIA_URL=${NEXT_PUBLIC_MEDIA_URL}
      - NEXT_PUBLIC_LIVEKIT_WS_URL=${NEXT_PUBLIC_LIVEKIT_WS_URL}
      - NEXT_PUBLIC_LIVEKIT_TOKEN=${NEXT_PUBLIC_LIVEKIT_TOKEN}
    volumes:
      - .:/app
    networks:
      - epic_stream_network

networks:
  epic_stream_network:
